#支付相关配置:
pay:
  internet:
    address: http://dd8j86.natappfree.cc #外网地址
  #支付宝相关配置
  alipay:
    openApiDomain: https://openapi.alipaydev.com/gateway.do #支付宝网关名
    pid: 2088102170073425 #商户ID
    appId: 2016080500173648 #应用ID
    # RSA私钥
    appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCbsBzYuMXWOxH/9or4fgxN+q1ZZvSJ+qk2snXSsh48ya2BSS/pckvw6HZRbElFZBNG4Szi9CSMxksn6oyPYe4gXbEoKpQK5xV2lEakitXaxw08S7WtdEcJGSe3rCms/4LzGiVPo9ovdpshEx9NRwMHJ99dxDLkYjJhlbgi8yZB1L81U6lzj7te6u7GqIuwsOCduBpYjoLJXrWWchk5hgst5ObkJ+7+WqmYtorMm2reuimeIs9nMy+qri+7IZ0nE6UpbYm3h/vJ/M3BKr6Kjzzf0wMP2cmP6LWhiNeDMbiNR2LXzXsYJ+er/2c4jz31Lw7KzHMqPplSuecFYjJw945DAgMBAAECggEBAJoJc2ER39wIcdS4z+Lwg6gbn6vW65ghA470nxKp3LT0LdC+4sKsrWpb9cS1yQD49QGqBMlAGXGXOAD0VcH/eKVZTdCZ4AOxg1Dhf8uI+fIOA5BmsAhABZCA7QUTN+DMpXl1ovja+yL+zJm627uPyPUphBy35EqGxaY7hgY+YNm741PiNgz4ahrg3bYSodD75P2b2+qD4Fr3F5ekuM2Ogz7eE92ebP7V595k6olZC5kgjiQ1Dcqnu9GZNpMERRHOVSwuf+w6HihsP5fHQP+jSiKxkgOqr5nDbtMrFaQM/MwQMYDRmWCQlfJvCsyg1C3yKSg8V2euI+PELaq7uca9nPECgYEA0D2BH/l2MH4d7QeyqG9C4BPVgy+ngpm54pRcyQw/JuiyjQC2Ic5IDWHodH9xQF4h5t5syJPCsA8iGj1vd+ckNqGYbZIDzcTFd5KaqPkwfs7xYD8SrZfljT9PbWo8tqkzV2Mz8syxyDQaYNVBKf1jORfwYfuTYL90I5lBr+jLH0UCgYEAv2UVMkB0zzjIjRO9YCpv9d93v/88QGzzk/JkdkxXy0oYTo0DMrwZT60DwuC+qiBnVtt2D2sF6CutyK06J+D8oVUJvLYSBCUng0TDa/axIaTZDtpsjzoFEPgl8H4ou0OP56qQujqqoUzXUgCe7FOOP6OpXhkpXv2BsHHEaFay6+cCgYBR7JB7OtJDm6o8UTX5S+RccZEjTkExgTb/K+0g7198+DkeffQpcpUoJqekBWtRrnbZ9BGKC4+hYiLBff/3hQjbMVHdcX9rmYkyVIviBD8O9G1Dtyyq/MJDgm/GFPCT0BcxvwZ19A/ROqZSCDPdyCEcGg3pDmdZvZh8VNPh18zpnQKBgQCBKHOvX7P0Czu7iHCprrmzUMR8+n7scxnE4zRMaKRueWgBykM4P5tNG1KIdiX0pL1X7e2z5eMslB1IaS3vr3KMZNiXUr7BsVkCyqqd9vH95ELeNSRBW0QD+ZGQw3I1PRilm4LjSafQBgzgN68HiDNcWtN2vsAebDDSo1OJnchMTQKBgQCt7z43BeO7MdDzY4k+Jgw+TVwK9fVVvZyzbybnVGpYuSl8ooZvMSHH3uLXL5OvLF6bY7E1BRqlWDpApkPX8Lk+JBx2Rjx0pmtPNg3fPk/PdY9Qr/LQfc29ZH0tM64TeO7DCwZHFF9Vxo4Ocng6nhhZy2xDt7Jhun1IixIk52zW/w==
    #支付宝公钥
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtGhJtg7sYOSqGHm2QfaX8vJKAemX9NQjdNNDeqafwaRsgNsBFuJjfwgYj6FEUbELL411y75BBpVL9fnldxIPfpHF/51sAC67WteezwAQuyYe6cds3zwVKNnDb7ykMVyHPyL2fq6gtO80aMYWgKGw/sJaem2AzfMhzOwdawL6G4Tlbmii9cIBC9dSToWxvP1pWHEQ2awbHma6UUoUWLXRk4s/Y7l7HCXThDj7iTGBoS0mSqXAgAvcvkATMAcDKfeVWosWinBfUOuF4cDS0Nm+R5WZ1s/1gL6fSLpQ3LDHGdYe0cRZ/+lT2CInug5nVMJtE5eRBB0RuSYP8YSv8cVzBwIDAQAB
    signType: RSA2 # 签名类型: RSA
    paramType: json #参数类型
    charSet: UTF-8 #编码
    notifyUrl: ${pay.internet.address}/thirdPay/aliPayBackUrl #后台通知地址
    returnUrl: ${pay.internet.address}/thirdPay/aliPayFrontUrl #前台回调地址
      #支付宝沙箱测试用户信息：
      #买家账号txdslh1900@sandbox.com
      #登录密码111111
    #支付密码111111

  #微信相关配置
  wxpay:
    appId: wxbfcccd6701fdead5 #应用授权ID
    mchId: 1526548491 #商户号
    key: 13050166540800000603130501665408 #API密钥
    notifyUrl: ${pay.internet.address}/thirdPay/wxPayBackUrl #异步接收微信支付结果通知的回调地址，通知url必须为外网可访问的url，不能携带参数。
  #银联支付相关
  unionpay:
    acpsdk:
      backUrl: ${pay.internet.address}/thirdPay/unionPayBackUrl #后台通知地址，填写接收银联后台通知的地址，必须外网能访问
      frontUrl: ${pay.internet.address}/thirdPay/unionPayFrontUrl #前台通知地址，填写银联前台通知的地址，必须外网能访问

